- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Make sure cache directory exists
      file:
        path: "{{ vagrant_home }}/cache/{{ ansible_distribution }}/{{ ansible_distribution_version }}/"
        state: directory
      when: vagrant_cache

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - common

#- hosts: master
#  become: yes
#  become_method: sudo
#  roles:
#    - client 

- hosts: master
  become: yes
  become_method: sudo
  roles:
    - master

- hosts: cluster
  become: yes
  become_method: sudo
  roles:
    - cluster

- hosts: gluster
  become: yes
  become_method: sudo
  roles:
    - gluster

- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - import_role:
        role: common
        tasks_from: yum_cache.yml
      delegate_to: "{{ item }}"
      with_items:
      - "master"
      - "node0"
      - "{{ 'node1' if external_glusterfs | bool else omit }}"
      when: vagrant_cache
