- hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - "global_vars.yml"
  roles:
    - common

- hosts: master
  become: yes
  become_method: sudo
  vars_files:
    - "global_vars.yml"
  roles:
    - master

- hosts: cluster
  become: yes
  become_method: sudo
  roles:
    - cluster

- hosts: gluster
  become: yes
  become_method: sudo
  vars_files:
    - "global_vars.yml"
  roles:
    - gluster

- import_playbook: yum_cache.yml
  when: vagrant_cache
