---
- name: Archive yum cache
  archive:
    path: "/var/cache/yum"
    dest: "/tmp/yum-{{ ansible_hostname }}.tgz"

- name: Copy yum cache to host
  fetch:
    src: "/tmp/yum-{{ ansible_hostname }}.tgz"
    dest: "{{ yum_cache_dir }}/"
    flat: true
  become: false

- set_fact:
    yum_cache_dir: "{{ yum_cache_dir }}"
