#- name: install ansible and Heketi utilities
#  yum: name={{ item }} state=present
#  with_items:
#    - ansible
#    - pyOpenSSL
#    - heketi-client
#    - heketi-templates

#- name: get openshift-ansible release 1.3
#  git: repo=https://github.com/openshift/openshift-ansible dest=/home/vagrant/openshift-ansible version=release-1.3

#- name: copy hosts.conf
#  copy: src=hosts.conf dest=/home/vagrant force=yes mode=0644

#- name: copy topology.json
#  copy: src=topology.json dest=/home/vagrant force=yes mode=0666

- name: get default DNS
  shell: grep nameserver /etc/resolv.conf | awk '{print $2}'
  register: cat_resolv

- name: copy dnsmasq.conf
  template: src=dnsmasq.conf dest=/etc force=yes mode=0644

- name: restart dnsmasq
  service: name=dnsmasq enabled=yes state=restarted

- name: setup eth0 DNS
  lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-eth0 line={{item}}
  with_items:
    - "PEERDNS=no"
    - "DNS1=127.0.0.1"

- name: restart NetworkManager
  service: name=NetworkManager enabled=yes state=restarted

- name: Open DNS port
  command: iptables -A INPUT -m state --state NEW -p udp --dport 53 -j ACCEPT

- name: save iptables
  command: service iptables save

#- name: setup resolv.conf 
#  lineinfile: dest=/etc/rc.d/rc.local regexp="^sed" line="sed -i '1s/^/nameserver 127.0.0.1\\n/' /etc/resolv.conf"
#
#- name: make rc.local executable
#  command: chmod a+x /etc/rc.d/rc.local
#
#- name: update resolv.conf
#  command: /etc/rc.local

#- name: get oc client
#  unarchive: src=https://github.com/openshift/origin/releases/download/v1.3.0/openshift-origin-client-tools-v1.3.0-3ab7af3d097b57f933eccef684a714f2368804e7-linux-64bit.tar.gz dest=/home/vagrant copy=no

#- name: copy oc to /usr/bin
#  command: cp /home/vagrant/openshift-origin-client-tools-v1.3.0-3ab7af3d097b57f933eccef684a714f2368804e7-linux-64bit/oc /usr/bin

#- name: install openshift this can take about 20 mins
#  command: ansible-playbook -i hosts.conf openshift-ansible/playbooks/byo/config.yml
#  args:
#      chdir: /home/vagrant
#      creates: /home/vagrant/.kube/config
#  become: yes
#  become_user: vagrant
#  environment:
#      ANSIBLE_HOST_KEY_CHECKING: False
#
#- name: login to openshift cluster
#  become: yes
#  become_user: vagrant
#  command: oc login https://192.168.10.90:8443 --insecure-skip-tls-verify=true --username=admin --password=admin
#  args:
#      chdir: /home/vagrant
#      creates: /home/vagrant/.kube/config

